### Cadastrar um novo produto
POST https://localhost:5001/api/produto/create
Content-Type: application/json

{
    "Nome" : "Elder scrolls 6",
    "Preco" : 90,
    "Quantidade": 3,
    "Descricao" : "Jogo que nunca vai sair",
    "CategoriaId" : 1
}

### Listar todos os produtos
GET https://localhost:5001/api/produto/list

### Buscar um produto pelo id
GET https://localhost:5001/api/produto/getbyid/1

### Deletar um produto pelo nome
DELETE https://localhost:5001/api/produto/delete/Harry

### Alterar um produto
PUT https://localhost:5001/api/produto/update
Content-Type: application/json

{
    "Id" : 1,
    "Nome" : "Half Life",
    "Preco" : 3.5
}
